services:
  kronize:
    image: ${REGISTRY_URL}/kronize/kronize:kronize-v1.0.13
    container_name: kronize
    restart: unless-stopped
    networks:
      - kronize-net
    ports:
      - "6182:8080"
    environment:
      - JWT_SECRET=${JWT_SECRET:?JWT_SECRET required}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - ADDR=:8080
      - REGISTRY_URL=${REGISTRY_URL:?REGISTRY_URL required}
      - TZ=${TZ}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - kronize-data:/data
      - kronize-scripts:/data/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    group_add:
      - "${DOCKER_GID:-999}"

  python-runner:
    image: ${REGISTRY_URL}/kronize/python-runner:python-runner-v1.0.4
    container_name: kronize-python-runner
    restart: unless-stopped

volumes:
  kronize-data:
  kronize-scripts:

networks:
  kronize-net:
